# Generated by Django 5.0.7 on 2024-08-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=64)),
                ('valor', models.IntegerField()),
                ('parcelas', models.IntegerField()),
            ],
        ),
    ]
