# Generated by Django 5.0.7 on 2024-09-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='data_inicial',
            field=models.CharField(default=27092002, max_length=10),
            preserve_default=False,
        ),
    ]
