# Generated by Django 5.0.7 on 2024-08-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_gastos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('A', 'Alimentação'), ('T', 'Transporte'), ('E', 'Entretenimento'), ('M', 'Moradia'), ('Edu', 'Educação'), ('S', 'Serviços'), ('SU', 'Saúde'), ('O', 'Outros')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
