# Generated by Django 5.0.7 on 2024-09-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_gastos_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data_inicial',
            field=models.CharField(max_length=5),
        ),
    ]
