# Generated by Django 5.0.7 on 2024-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_gastos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Entretenimento', 'Entretenimento'), ('Moradia', 'Moradia'), ('Educação', 'Educação'), ('Serviços', 'Serviços'), ('Saúde', 'Saúde'), ('Outros', 'Outros')], max_length=30),
        ),
    ]
