# Generated by Django 5.0.7 on 2024-09-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_gastos_data_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
