# Generated by Django 5.0.7 on 2024-09-18 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_gastos_usuario_alter_user_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
