# Generated by Django 5.0.7 on 2024-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_gastos_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='parcelado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
