# Generated by Django 5.0.7 on 2024-10-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_gastos_categoria_entradadinheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadinheiro',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000),
            preserve_default=False,
        ),
    ]
