# Generated by Django 5.0.7 on 2024-10-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_entradadinheiro_saldo_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradadinheiro',
            name='saldo_anterior',
        ),
    ]
