# Generated by Django 5.0.7 on 2024-10-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_entradadinheiro_saldo_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadinheiro',
            name='origem',
            field=models.CharField(default=123, max_length=70),
            preserve_default=False,
        ),
    ]
